### ISSUE TITLE
"cannot pickle 'weakref.ReferenceType' object" on linux with start_method "spawn"

### ISSUE THREAD

**Issue by h3po** [flaviovs/mpubsub#1]
Hi, thank you for the tutorial and what looks to be a good library. However I can't get it to run on linux as long as mp.set_start_method('spawn') is used. I'm currently on python 3.12, but the same thing happens with a python 3.7 venv. It must be a plattform issue then? I can't figure out which object is being passed that is not pickleable. I tried refactoring the demo to remove all global variables, moving the subscriber and publisher functions into separate modules and removing all accesses to the logging library.
Do you have an Idea what might cause this? I'd like to stick with spawn instead of fork to not copy a large amount of global imports from the main into each process.

3.7:
```
2024-05-24 16:31:12,247 I MainProcess: Starting demo with 3 publishers and 3 subscribers
Traceback (most recent call last):
  File "demo.py", line 165, in <module>
    main()
  File "demo.py", line 137, in main
    broker_process.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle weakref objects
```

3.12:
```
2024-05-24 16:36:40,439 I MainProcess: Starting demo with 3 publishers and 3 subscribers
Traceback (most recent call last):
  File "/home/h3po/git/github/mpubsub/src/demo.py", line 165, in <module>
    main()
  File "/home/h3po/git/github/mpubsub/src/demo.py", line 137, in main
    broker_process.start()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.12/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref.ReferenceType' object
```

**Comment by h3po** [comment]
I figured it out with the help of chatgpt. The broker class itself is being pickled because the start method is contained in it. Moving the class instantiation into the subprocess fixes the error. I then use an mp.Queue to return the address to main. We no longer have consistent authkeys between the processes, so I chose to derive it from a given password.

```
diff --git a/demo.py b/demo.py
index b8cefa6..7156ef0 100644
--- a/demo.py
+++ b/demo.py
@@ -19,9 +19,9 @@ logger = logging.getLogger(__name__)
 
 # Now let's start a few publishers. Each one has its own PubSub
 # object, and a Bridge connected to the broker.
-def publisher(address, delay_min, delay_max, n):
+def publisher(address, authkey, delay_min, delay_max, n):
     logger.info('Starting up')
-    pubsub = PubSub(address)
+    pubsub = PubSub(address, authkey)
 
     pubsub.connect()
 
@@ -45,10 +45,10 @@ def publisher(address, delay_min, delay_max, n):
     pubsub.disconnect()
 
 
-def subscriber(address, n):
+def subscriber(address, authkey, n):
     logger.info('Starting up')
 
-    pubsub = PubSub(address)
+    pubsub = PubSub(address, authkey)
 
     msg_sequence: Dict[str, int] = {}
 
@@ -92,6 +92,11 @@ def subscriber(address, n):
         pubsub.poll(None)
     pubsub.disconnect()
 
+def broker(password: str, return_queue: mp.Queue) -> None:
+    authkey = password.encode("utf-8")
+    broker = Broker(authkey=authkey)
+    return_queue.put((broker.address, authkey))
+    broker.start()
 
 def main() -> None:
     parser = argparse.ArgumentParser(
@@ -117,6 +122,8 @@ def main() -> None:
                         default=0.2,
                         help=('seconds to wait per subscriber before '
                               'starting publishers'))
+    parser.add_argument('--password', type=str, default='password',
+                        help='the password to use on the broker')
     args = parser.parse_args()
 
     logger.info('Starting demo with %d publishers and %d subscribers',
@@ -126,20 +133,19 @@ def main() -> None:
 
     processes = []
 
-    # Get the broker object.
-    broker = Broker(None)
-
-    # Grab its address.
-    address = broker.address
+    address_queue = mp.Queue()
 
     # Start the broker in a separate process.
-    broker_process = mp.Process(target=broker.start, name='broker')
+    broker_process = mp.Process(target=broker, args=(args.password, address_queue,), name='broker')
     broker_process.start()
     processes.append(broker_process)
 
+    # Grab its address.
+    address, authkey = address_queue.get()
+
     # Start subscribers.
     for n in range(args.subscribers):
-        proc = mp.Process(target=subscriber, name=f'sub{n}', args=(address, n))
+        proc = mp.Process(target=subscriber, name=f'sub{n}', args=(address, authkey, n))
         proc.start()
         processes.append(proc)
 
@@ -152,7 +158,7 @@ def main() -> None:
     # Start publishers.
     for n in range(args.publishers):
         proc = mp.Process(target=publisher, name=f'PUB{n}',
-                          args=(address, min(args.delay_min, args.delay_max),
+                          args=(address, authkey, min(args.delay_min, args.delay_max),
                                 args.delay_max, n))
         proc.start()
         processes.append(proc)
```

**Comment by flaviovs** [comment]
Hi @h3po - sorry for the delay.

The demo was always intended to be a just that: a demo. So MP start methods other than the default were never tested. 

BTW, AFAIK Linux's _fork(2)_ does copy-on-write so as long as your parent and children processes don't write to those globals, the overhead is negligible. You can always use `del` in your start-up code to remove references to large global vars that are changed by the parent, though. I think it is important to mention this because spawning a new process is much slower than fork (and depending on how the application is structured, those globals get created anyway).

Anyways, thanks for posting your solution, it was a clever one. I'll keep it in mind in case someone faces the same issue.

**Comment by h3po** [comment]
> The demo was always intended to be a just that: a demo. So MP start methods other than the default were never tested.

I mention it because "spawn" is what you are using in the demo: https://github.com/flaviovs/mpubsub/blob/a91981fed847fe5362ab32f3c1438556b603aa71/demo.py#L125

> BTW, AFAIK Linux's _fork(2)_ does copy-on-write so as long as your parent and children processes don't write to those globals, the overhead is negligible. You can always use `del` in your start-up code to remove references to large global vars that are changed by the parent, though. I think it is important to mention this because spawning a new process is much slower than fork (and depending on how the application is structured, those globals get created anyway).

Yes, that's what the docs say. When I read that, in my mind it meant that there's more overhead in the interpreter because of the larger global state dictionary. I guess I'll try to benchmark it once I have some actual use-cases implemented. Right now I'm looking around for solutions to have encryption on top of the communication sockets; it looks to me like that will be hard to achieve with mp.connection without resorting to monkey-patching

**Comment by flaviovs** [comment]
Dang, I totally forgot that I had added that `set_start_method()` call. :roll_eyes:. Thanks for pointing it out.

Anyways, having encryption was on the top of my list for the package, but it proved very difficult with `multiprocessing` so I gave up. If you come up with something that can be shared and is generic enough, I'm more than happy to merge a PR.
